# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(831, 570)
        self.EncodeViewer = QtWidgets.QTextBrowser(Form)
        self.EncodeViewer.setGeometry(QtCore.QRect(440, 10, 381, 551))
        self.EncodeViewer.setObjectName("EncodeViewer")
        self.EncodeB = QtWidgets.QPushButton(Form)
        self.EncodeB.setGeometry(QtCore.QRect(350, 10, 81, 51))
        self.EncodeB.setObjectName("EncodeB")
        self.DecodeB = QtWidgets.QPushButton(Form)
        self.DecodeB.setGeometry(QtCore.QRect(350, 522, 81, 41))
        self.DecodeB.setObjectName("DecodeB")
        self.DecodeViewer = QtWidgets.QTextEdit(Form)
        self.DecodeViewer.setGeometry(QtCore.QRect(0, 10, 341, 551))
        self.DecodeViewer.setObjectName("DecodeViewer")
        self.methodBox = QtWidgets.QComboBox(Form)
        self.methodBox.setGeometry(QtCore.QRect(350, 240, 81, 41))
        self.methodBox.setObjectName("methodBox")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.fileB = QtWidgets.QPushButton(Form)
        self.fileB.setGeometry(QtCore.QRect(350, 120, 81, 51))
        self.fileB.setObjectName("fileB")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.EncodeB.setText(_translate("Form", "Encode"))
        self.DecodeB.setText(_translate("Form", "Decode"))
        self.methodBox.setItemText(0, _translate("Form", "Arifmetic"))
        self.methodBox.setItemText(1, _translate("Form", "LZSS"))
        self.fileB.setText(_translate("Form", "Файл"))



class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.ui = Ui_Form()
        self.ui.setupUi(self)


app = QtWidgets.QApplication(sys.argv)
mainWindwow = MainWindow()
widget = QtWidgets.QStackedWidget()
widget.addWidget(mainWindwow)
widget.setFixedHeight(580)
widget.setFixedWidth(821)
widget.show()

sys.exit(app.exec_())